// Code generated by entc, DO NOT EDIT.

package profile

const (
	// Label holds the string label denoting the profile type in the database.
	Label = "profile"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDesc holds the string denoting the desc field in the database.
	FieldDesc = "desc"
	// FieldQq holds the string denoting the qq field in the database.
	FieldQq = "qq"
	// FieldWechat holds the string denoting the wechat field in the database.
	FieldWechat = "wechat"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldImg holds the string denoting the img field in the database.
	FieldImg = "img"
	// FieldAvatar holds the string denoting the avatar field in the database.
	FieldAvatar = "avatar"
	// Table holds the table name of the profile in the database.
	Table = "profiles"
)

// Columns holds all SQL columns for profile fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldDesc,
	FieldQq,
	FieldWechat,
	FieldEmail,
	FieldImg,
	FieldAvatar,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
