// Code generated by entc, DO NOT EDIT.

package article

const (
	// Label holds the string label denoting the article type in the database.
	Label = "article"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldCid holds the string denoting the cid field in the database.
	FieldCid = "cid"
	// FieldDesc holds the string denoting the desc field in the database.
	FieldDesc = "desc"
	// FieldContent holds the string denoting the content field in the database.
	FieldContent = "content"
	// FieldImg holds the string denoting the img field in the database.
	FieldImg = "img"
	// Table holds the table name of the article in the database.
	Table = "articles"
)

// Columns holds all SQL columns for article fields.
var Columns = []string{
	FieldID,
	FieldTitle,
	FieldCid,
	FieldDesc,
	FieldContent,
	FieldImg,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
